### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by Snake231088** [propelorm/PropelLaravel#11]
Have you intention to continue support for this project?
I was planning to integrate it in my projects.
Thx

**Comment by SCIF** [comment]
@Snake231088 , hey! We use it on some prod projects. Also, i almost finished new version. A lot of code did rewritten. Added support of 5.2 and new awesome bootstrap cli command.

**Comment by Snake231088** [comment]
Thx! When the new release? :)
(I'll close the issue after your response :D)

**Comment by SCIF** [comment]
@Snake231088 , i will try to allocate time on next week to push it. Release will not be issued until tests will have passed fully. But new code will be pushed even without release.

**Comment by Snake231088** [comment]
Please push if you have time.
Thx.

**Comment by SCIF** [comment]
@Snake231088 , i pushed. https://github.com/propelorm/PropelLaravel/commit/736ba5d6f1df4b0e2b0cbcaf21c820bbddb8c81b Spent some time to update docs but not cleary still. Introduced new command `propel:laravel:init`. Use that with caution and only on test installations. Working to cover it tests now.
