### ISSUE TITLE
config/propel.php broken

### ISSUE THREAD

**Issue by Snake231088** [propelorm/PropelLaravel#13]
In develop branch, the config/propel.php is broken.
No connection defined for database "mysql". Did you forget to define a connection or is it wrong written?
In the configuration is expected "default" and not "mysql" but the default should be "mysql"
The configuration in master branch is better.

**Comment by SCIF** [comment]
@Snake231088 , hi!

Which command works incorrect for you? Default name is just default name since everything works fine. All commands should use default connection name from config and any name should not be an issue.

**Comment by Snake231088** [comment]
Sorry,
my configuration was bad. I had mysql in my schema.xml :(
