### ISSUE TITLE
Add users class to schema file in init process

### ISSUE THREAD

**Issue by ghost** [propelorm/PropelLaravel#15]
If the init process `php artisan propel:laravel:init` is changing Laravel Auth to Propel it should also add the tables `users` and `password_reminders` to the default `database/schema.xml` file while creating it.

https://github.com/propelorm/PropelLaravel/blob/develop/resources/auth_schema.xml
(this link might be outdated in the future because it links to the `develop` branch)

**Comment by SCIF** [comment]
@JHGitty , it's enough just copy that schema and it will take in account of ORM, isn't it? I was sure that it's so. That auth schema copies to your database directory during `propel:laravel:init`

**Comment by ghost** [comment]
As I can see in the code there is already a function to copy an `auth_schema.xml` file through the init process. I did something wrong while running `propel:laravel:init` and so didn't got it. Sorry. Thank you!
