### ISSUE TITLE
Lumen Installation Fails

### ISSUE THREAD

**Issue by byrnedo** [propelorm/PropelLaravel#18]
When I try and run any artisan command after installing on Lumen 5.x I get 

```
PHP Fatal error:  Uncaught exception 'ErrorException' with message 'array_filter() expects parameter 1 to be array, null given' in /home/donal/dev/api/vendor/propel/propel-laravel/config/propel.php:82
```

**Comment by SCIF** [comment]
Hi @byrnedo!

It's better to try using [develop](https://github.com/propelorm/PropelLaravel/tree/develop) branch. The config issue fixed in it.
