### ISSUE TITLE
Auto map field

### ISSUE THREAD

**Issue by gtokung** [propelorm/PropelLaravel#20]
Hi,

Do you have the way to auto map field before save?
Not do like this for all fileds ($author->setFirstName('Leo'); ..... )

**Comment by SCIF** [comment]
@gtokung , hi!

Do you mean to fill model from array data? http://propelorm.org/documentation/reference/active-record.html#generic-getters-and-setters Use `fromArray()` method in this case. And it's not related to PropelLaravel.

**Comment by gtokung** [comment]
Thank You.
