### ISSUE TITLE
I want to build ViewTable unsuccessfully.

### ISSUE THREAD

**Issue by gtokung** [propelorm/PropelLaravel#22]
```
<table name="table_name" phpName="TableName" readOnly="true" skipSql="true">
...
</table>
```

I'm not sure what I was doing.

**Comment by SCIF** [comment]
@gtokung , what's for do you about Propel2 usage here? It's not related to adapter. Sorry, but I close this issue. Also, close please your another issues if they not related to adapter. Consult [support](http://propelorm.org/support.html) page please
