### ISSUE TITLE
Config file propel.php gets loaded before database.php, making Laravel crash

### ISSUE THREAD

**Issue by lucapasquini** [propelorm/PropelLaravel#9]
Hi,

I'm having some issues integrating Propel in Laravel 5.1.24. I added "minimum-stability":"alpha" in composer.json and added Propel laravel using "composer require propel/propel-laravel dev-master".

Any attempt to run Laravel or call Artisan commands after that gives me this output (real project path is replaced with /path/to/project):
PHP Warning:  array_filter() expects parameter 1 to be array, null given in /path/to/project/config/propel.php on line 83
PHP Warning:  array_map(): Argument #2 should be an array in /path/to/project/config/propel.php on line 84
PHP Fatal error:  Unsupported operand types in /path/to/project/vendor/propel/propel-laravel/src/RuntimeServiceProvider.php on line 74

It seems that the issue is related to app('config')->get('database.connections'), which is NULL when calling var_dump() from propel.php. Replacing propel.php with return []; gives no errors, but obviously doesn't work. Echoing a message in propel.php and database.php reveals that propel.php is loaded before database.php

The project is running on a Ubuntu 14.04 LTS server with PHP 5.5.9. composer.lock file says that propel/propel is 2.0.0-alpha5 (reference 75f775cf6de41595d1240885eea5fa5d475d228d), propel/propel-laravel is dev-master (reference 68a1d0edc784a89fe8853672425cd6198dd83aa1) and laravel/framework is 5.1.24 (reference 875baf2d1645ce23e2ec0bf94fa7bb3e7fbfd6ed).

Any suggestions? Many thanks!

**Comment by julienvincent** [comment]
+1 same issue

**Comment by SCIF** [comment]
Hey guys! @lucapasquini @julienvincent 

Sorry for stagnation in project. In fact that config issue fixed already but i didn't release new version and not merge develop branch. Next release config approach will be changed in favor of «plain» config. You can just copy it to your app config from here: https://github.com/propelorm/PropelLaravel/blob/develop/config/propel.php

I have couple of not finished features which will in next release. Really doubt that i can finish until Christmas but not much later.

**Comment by julienvincent** [comment]
Thank you very much. That works.
